definitions:
  model.ChromaQueryResultsDTO:
    properties:
      distance:
        type: number
      id:
        type: string
      metadata:
        $ref: '#/definitions/model.Metadata'
      text:
        type: string
    type: object
  model.Metadata:
    properties:
      book:
        type: string
      chapter:
        type: string
      verse:
        type: string
    type: object
  model.QueryDTO:
    properties:
      query:
        type: string
    type: object
  model.QueryResultsDTO:
    properties:
      result:
        items:
          $ref: '#/definitions/model.ChromaQueryResultsDTO'
        type: array
    type: object
  model.StatusDTO:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  model.VectorizeDTO:
    properties:
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /query:
    post:
      consumes:
      - application/json
      description: query the vector database
      parameters:
      - description: query
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/model.QueryDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.QueryResultsDTO'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: query the vector database
      tags:
      - query
  /vectorize:
    post:
      consumes:
      - application/json
      description: start the vectorization process in the background
      parameters:
      - description: query
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/model.VectorizeDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StatusDTO'
      summary: start the vectorization process in the background
      tags:
      - vectorize
swagger: "2.0"
